version: '3'
services:
    lipotes-vexillifer:
        image: uniqueding/lipotes-vexillifer:latest
        ports:
          - 80:80
        restart: always
        volumes:
          - ./path/to/note:/lipotes-vexillifer/note
          - ./path/to/picture:/lipotes-vexillifer/picture
          - ./path/to/ebook:/lipotes-vexillifer/ebook
          - ./path/to/config:/lipotes-vexillifer/config
          - ./path/to/nginx:/etc/nginx/conf.d/
